/**
 * The standalone review page shipped inside every `.html` file generated by
 * `buildReviewFile`. Everything here — markup, styles, and behavior — has to
 * be inlined and dependency-free: the file is emailed around and opened
 * offline, so it cannot fetch fonts, scripts, or anything else over the
 * network. See `build-review-file.ts` for how the placeholders below are
 * filled in.
 *
 * Design tokens are copied from `src/app/globals.css` (the warm dark theme /
 * gold accent) rather than imported, for the same self-containment reason.
 * Font families fall back to system stacks that read close to DM Serif
 * Display / Outfit without a network fetch.
 */

export interface ReviewTemplateData {
  /** Random id embedded in the page and used as the localStorage autosave key. */
  docId: string;
  /** Note title — used for <title> and the on-page heading. */
  title: string;
  /** Pre-escaped title, safe to inline into HTML text nodes/attributes. */
  titleHtml: string;
  /** Author's display name, shown in the page intro. Empty string if unset. */
  authorName: string;
  /** Author's email, used to prefill the "Send back" mailto. Empty string if unset. */
  authorEmail: string;
  /** The note rendered to HTML via markdown-it (html:false, so it's pre-sanitized). */
  bodyHtml: string;
  /** Sanitized filename stem (no extension) used to name the downloaded JSON. */
  filenameStem: string;
}

export function renderReviewTemplate(data: ReviewTemplateData): string {
  const { docId, titleHtml, authorName, authorEmail, bodyHtml, filenameStem } = data;
  const authorLine = authorName
    ? `${escapeHtml(authorName)} sent you this draft to review.`
    : "You've been sent this draft to review.";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Review: ${titleHtml}</title>
<style>
${STYLES}
</style>
</head>
<body>
<div class="review-shell">

  <header class="review-intro">
    <p class="review-intro-eyebrow">Fragment · Review</p>
    <h1 class="review-intro-title">${titleHtml}</h1>
    <p class="review-intro-sub">${authorLine} Select any text below to leave a comment, or add a general note in the sidebar. When you're done, hit "Send back".</p>
  </header>

  <div class="review-layout">
    <main class="review-doc-wrap">
      <article id="doc" class="review-doc">
${bodyHtml}
      </article>
      <p class="review-footer">Written with Fragment · <a href="https://github.com/anurieli/fragment" rel="noopener">github.com/anurieli/fragment</a></p>
    </main>

    <aside class="review-sidebar">
      <div class="review-sidebar-section">
        <label class="review-label" for="reviewer-name">Your name</label>
        <p class="review-hint">Shown to the author alongside your comments. Saved on this device for next time.</p>
        <input id="reviewer-name" class="review-input" type="text" placeholder="Your name" autocomplete="name">
      </div>

      <div class="review-sidebar-section review-edit-toggle-row">
        <label class="review-checkbox-label">
          <input id="edit-toggle" type="checkbox">
          <span>Edit the text directly</span>
        </label>
        <p class="review-hint">Optional — turns the document editable so you can make direct changes instead of (or alongside) comments.</p>
      </div>

      <div class="review-sidebar-section review-comments-section">
        <div class="review-comments-header">
          <span class="review-label">Comments</span>
          <span id="comments-count" class="review-count">0</span>
        </div>
        <p class="review-hint">Highlighted comments are anchored to text in the document. Click one to jump to it.</p>
        <div id="comments-list" class="review-comments-list"></div>
      </div>

      <div class="review-sidebar-section">
        <label class="review-label" for="note-comment-body">Add a general comment</label>
        <p class="review-hint">Not tied to a specific passage — use this for overall feedback.</p>
        <textarea id="note-comment-body" class="review-textarea" rows="3" placeholder="Overall thoughts..."></textarea>
        <button id="add-note-comment" class="review-btn review-btn-secondary" type="button">Add comment</button>
      </div>

      <div class="review-sidebar-section review-send-section">
        <button id="send-back" class="review-btn review-btn-primary" type="button">Send back</button>
        <p id="send-status" class="review-hint review-send-status" role="status"></p>
      </div>
    </aside>
  </div>
</div>

<div id="selection-popup" class="review-selection-popup" hidden>
  <button id="selection-comment-btn" type="button" class="review-btn review-btn-pill">+ Comment</button>
  <div id="selection-comment-form" class="review-selection-form" hidden>
    <textarea id="selection-comment-body" class="review-textarea" rows="2" placeholder="Your comment..." autofocus></textarea>
    <div class="review-selection-form-actions">
      <button id="selection-comment-cancel" type="button" class="review-btn review-btn-ghost">Cancel</button>
      <button id="selection-comment-save" type="button" class="review-btn review-btn-primary review-btn-sm">Add</button>
    </div>
  </div>
</div>

<script>
${SCRIPT.replace("__DOC_ID__", JSON.stringify(docId))
  .replace("__TITLE__", JSON.stringify(data.title))
  .replace("__AUTHOR_NAME__", JSON.stringify(authorName))
  .replace("__AUTHOR_EMAIL__", JSON.stringify(authorEmail))
  .replace("__FILENAME_STEM__", JSON.stringify(filenameStem))}
</script>
</body>
</html>`;
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

const STYLES = `
  :root {
    --color-bg: #0c0c0b;
    --color-bg-warm: #111110;
    --color-surface: #161614;
    --color-surface-2: #1c1b18;
    --color-surface-3: #242320;
    --color-surface-hover: #2a2923;
    --color-gold: #e8b931;
    --color-gold-hover: #f0c94e;
    --color-gold-muted: rgba(232, 185, 49, 0.16);
    --color-gold-strong: rgba(232, 185, 49, 0.3);
    --color-text-primary: #e4e0d5;
    --color-text-secondary: #9e9a87;
    --color-text-muted: #8a8574;
    --color-text-faint: #6b6757;
    --color-border: rgba(255, 245, 200, 0.08);
    --color-border-strong: rgba(255, 245, 200, 0.14);
    --font-display: Georgia, "Times New Roman", serif;
    --font-body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    --font-mono: "SF Mono", "Cascadia Code", Menlo, Consolas, monospace;
    --radius-sm: 6px;
    --radius-default: 10px;
    --radius-lg: 14px;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body {
    background: var(--color-bg);
    color: var(--color-text-primary);
    font-family: var(--font-body);
    font-size: 16px;
    line-height: 1.65;
    -webkit-font-smoothing: antialiased;
  }
  .review-shell { max-width: 1180px; margin: 0 auto; padding: 2.5rem 1.5rem 5rem; }
  .review-intro { max-width: 720px; margin: 0 auto 2.5rem; }
  .review-intro-eyebrow {
    font-family: var(--font-mono); font-size: 11px; letter-spacing: 0.08em; text-transform: uppercase;
    color: var(--color-gold); margin: 0 0 0.5rem;
  }
  .review-intro-title { font-family: var(--font-display); font-size: 2rem; line-height: 1.25; margin: 0 0 0.6rem; }
  .review-intro-sub { color: var(--color-text-secondary); font-size: 14px; margin: 0; max-width: 60ch; }
  .review-layout { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: 2.5rem; align-items: start; }
  @media (max-width: 900px) {
    .review-layout { grid-template-columns: 1fr; }
    .review-sidebar { position: static; order: -1; }
  }
  .review-doc-wrap { min-width: 0; }
  .review-doc {
    background: var(--color-surface); border: 1px solid var(--color-border); border-radius: var(--radius-lg);
    padding: 2.5rem; font-size: 16px; line-height: 1.75;
  }
  .review-doc[contenteditable="true"] { outline: 2px dashed var(--color-gold-strong); outline-offset: 6px; cursor: text; }
  .review-doc h1, .review-doc h2, .review-doc h3 { font-family: var(--font-display); line-height: 1.3; margin: 1.4em 0 0.5em; }
  .review-doc h1 { font-size: 1.8rem; }
  .review-doc h2 { font-size: 1.4rem; }
  .review-doc h3 { font-size: 1.15rem; }
  .review-doc p { margin: 0 0 1em; }
  .review-doc a { color: var(--color-gold); }
  .review-doc blockquote { border-left: 3px solid var(--color-gold); padding-left: 1rem; margin: 1em 0; color: var(--color-text-secondary); }
  .review-doc code { font-family: var(--font-mono); background: var(--color-surface-2); padding: 0.15em 0.4em; border-radius: 4px; font-size: 0.9em; }
  .review-doc pre { background: var(--color-surface-2); padding: 1rem; border-radius: 8px; overflow-x: auto; }
  .review-doc pre code { background: none; padding: 0; }
  .review-doc ul, .review-doc ol { padding-left: 1.4rem; margin: 0 0 1em; }
  mark.review-mark {
    background: var(--color-gold-muted); color: inherit; border-bottom: 2px solid var(--color-gold);
    padding: 0 1px; border-radius: 2px; cursor: pointer;
  }
  mark.review-mark.flash { background: var(--color-gold-strong); }
  .review-footer {
    font-family: var(--font-mono); font-size: 11px; color: var(--color-text-faint);
    text-align: center; margin: 2rem 0 0;
  }
  .review-footer a { color: var(--color-text-faint); }
  .review-sidebar {
    position: sticky; top: 1.5rem; display: flex; flex-direction: column; gap: 1.25rem;
    background: var(--color-surface); border: 1px solid var(--color-border); border-radius: var(--radius-lg);
    padding: 1.5rem;
  }
  .review-sidebar-section { border-top: 1px solid var(--color-border); padding-top: 1.25rem; }
  .review-sidebar-section:first-child { border-top: none; padding-top: 0; }
  .review-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: var(--color-text-muted); font-weight: 600; display: block; }
  .review-hint { font-size: 12px; color: var(--color-text-faint); margin: 0.35rem 0 0.6rem; line-height: 1.5; }
  .review-input, .review-textarea {
    width: 100%; background: var(--color-surface-2); border: 1px solid var(--color-border-strong);
    border-radius: var(--radius-sm); color: var(--color-text-primary); font-family: inherit; font-size: 13px;
    padding: 8px 10px; outline: none; resize: vertical;
  }
  .review-input:focus, .review-textarea:focus { border-color: var(--color-gold); }
  .review-checkbox-label { display: flex; align-items: center; gap: 8px; font-size: 13px; color: var(--color-text-secondary); cursor: pointer; }
  .review-comments-header { display: flex; align-items: center; justify-content: space-between; }
  .review-count { font-family: var(--font-mono); font-size: 11px; color: var(--color-text-faint); }
  .review-comments-list { display: flex; flex-direction: column; gap: 8px; max-height: 320px; overflow-y: auto; }
  .review-comment-card {
    background: var(--color-surface-2); border: 1px solid var(--color-border-strong); border-radius: var(--radius-sm);
    padding: 10px 12px; cursor: pointer; position: relative;
  }
  .review-comment-card:hover { border-color: var(--color-gold-strong); }
  .review-comment-excerpt { font-size: 11px; color: var(--color-gold); font-family: var(--font-mono); margin: 0 0 4px; }
  .review-comment-body { font-size: 13px; color: var(--color-text-primary); margin: 0; white-space: pre-wrap; }
  .review-comment-delete {
    position: absolute; top: 6px; right: 6px; background: none; border: none; color: var(--color-text-faint);
    cursor: pointer; font-size: 14px; line-height: 1; padding: 2px 4px;
  }
  .review-comment-delete:hover { color: var(--color-text-primary); }
  .review-empty { font-size: 12px; color: var(--color-text-faint); font-style: italic; }
  .review-btn {
    font-family: inherit; font-size: 13px; font-weight: 500; border-radius: var(--radius-sm); border: 1px solid transparent;
    padding: 9px 14px; cursor: pointer; transition: all 0.12s ease;
  }
  .review-btn-primary { background: var(--color-gold); color: #1a1608; width: 100%; }
  .review-btn-primary:hover { background: var(--color-gold-hover); }
  .review-btn-secondary { background: var(--color-surface-3); color: var(--color-text-secondary); border-color: var(--color-border-strong); width: 100%; margin-top: 8px; }
  .review-btn-secondary:hover { color: var(--color-text-primary); }
  .review-btn-ghost { background: transparent; color: var(--color-text-muted); }
  .review-btn-ghost:hover { color: var(--color-text-primary); }
  .review-btn-sm { padding: 6px 12px; font-size: 12px; }
  .review-send-status { min-height: 1.2em; }
  .review-selection-popup { position: fixed; z-index: 40; }
  .review-btn-pill { background: var(--color-surface-3); color: var(--color-text-primary); border: 1px solid var(--color-gold-strong); box-shadow: 0 4px 16px rgba(0,0,0,0.4); }
  .review-btn-pill:hover { background: var(--color-gold); color: #1a1608; }
  .review-selection-form {
    margin-top: 6px; background: var(--color-surface-3); border: 1px solid var(--color-border-strong);
    border-radius: var(--radius-default); padding: 10px; width: 240px; box-shadow: 0 8px 24px rgba(0,0,0,0.5);
  }
  .review-selection-form-actions { display: flex; justify-content: flex-end; gap: 6px; margin-top: 8px; }
`;

/**
 * Vanilla JS, dependency-free, inlined into the generated review page.
 * `__DOC_ID__` / `__TITLE__` / `__AUTHOR_NAME__` / `__AUTHOR_EMAIL__` /
 * `__FILENAME_STEM__` are replaced with JSON-encoded literals by
 * `renderReviewTemplate` above.
 */
const SCRIPT = `(function () {
  "use strict";

  var DOC_ID = __DOC_ID__;
  var TITLE = __TITLE__;
  var AUTHOR_NAME = __AUTHOR_NAME__;
  var AUTHOR_EMAIL = __AUTHOR_EMAIL__;
  var FILENAME_STEM = __FILENAME_STEM__;
  var STORAGE_KEY = "fragment-review:" + DOC_ID;
  var NAME_KEY = "fragment-review:reviewer-name";
  var CONTEXT_LEN = 30;

  var docEl = document.getElementById("doc");
  var nameInput = document.getElementById("reviewer-name");
  var editToggle = document.getElementById("edit-toggle");
  var commentsListEl = document.getElementById("comments-list");
  var commentsCountEl = document.getElementById("comments-count");
  var noteBodyInput = document.getElementById("note-comment-body");
  var addNoteBtn = document.getElementById("add-note-comment");
  var sendBtn = document.getElementById("send-back");
  var sendStatusEl = document.getElementById("send-status");
  var selectionPopup = document.getElementById("selection-popup");
  var selectionCommentBtn = document.getElementById("selection-comment-btn");
  var selectionForm = document.getElementById("selection-comment-form");
  var selectionBody = document.getElementById("selection-comment-body");
  var selectionSave = document.getElementById("selection-comment-save");
  var selectionCancel = document.getElementById("selection-comment-cancel");

  var originalText = docEl.textContent;
  var comments = []; // {id, anchorText, prefix, suffix, body}
  var pendingRange = null;

  function genId() {
    return "c" + Math.random().toString(36).slice(2, 9) + Date.now().toString(36);
  }

  // ---------------------------------------------------------------------
  // Persistence — autosaves on every change, keyed by the doc's id so
  // reopening the same file in the same browser resumes where you left off.
  // ---------------------------------------------------------------------
  function save() {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({
        reviewerName: nameInput.value,
        comments: comments,
        edited: !!editToggle.checked,
      }));
      if (nameInput.value.trim()) {
        localStorage.setItem(NAME_KEY, nameInput.value);
      }
    } catch (e) { /* storage unavailable — best effort, never block the UI */ }
  }

  function restore() {
    var restoredComments = false;
    try {
      var raw = localStorage.getItem(STORAGE_KEY);
      if (raw) {
        var data = JSON.parse(raw);
        if (data && typeof data.reviewerName === "string" && data.reviewerName) {
          nameInput.value = data.reviewerName;
        }
        if (data && Array.isArray(data.comments)) {
          comments = data.comments;
          restoredComments = true;
        }
        if (data && data.edited) {
          editToggle.checked = true;
          docEl.setAttribute("contenteditable", "true");
        }
      }
      if (!nameInput.value) {
        var savedName = localStorage.getItem(NAME_KEY);
        if (savedName) nameInput.value = savedName;
      }
    } catch (e) { /* corrupt/unavailable storage — start fresh */ }

    if (restoredComments) {
      comments.forEach(function (c) {
        if (c.anchorText) applyMarkForComment(c);
      });
    }
    renderCommentList();
  }

  // ---------------------------------------------------------------------
  // DOM Range <-> plain-text offset helpers. #doc's rendered textContent is
  // the coordinate space every anchorText/prefix/suffix is computed against.
  // ---------------------------------------------------------------------
  function resolveBoundary(node, offset) {
    if (node.nodeType === Node.TEXT_NODE) return { node: node, offset: offset };
    if (offset >= node.childNodes.length) {
      var last = node.childNodes[node.childNodes.length - 1];
      if (!last) return { node: node, offset: 0 };
      if (last.nodeType === Node.TEXT_NODE) return { node: last, offset: last.textContent.length };
      return resolveBoundary(last, last.childNodes.length);
    }
    var child = node.childNodes[offset];
    if (child.nodeType === Node.TEXT_NODE) return { node: child, offset: 0 };
    return resolveBoundary(child, 0);
  }

  function getTextOffset(root, node, offset) {
    var resolved = resolveBoundary(node, offset);
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var total = 0;
    var current;
    while ((current = walker.nextNode())) {
      if (current === resolved.node) return total + resolved.offset;
      total += current.textContent.length;
    }
    return total;
  }

  function findRangeForOffsets(root, start, end) {
    var walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, null);
    var total = 0;
    var current;
    var range = document.createRange();
    var startSet = false, endSet = false;
    while ((current = walker.nextNode())) {
      var len = current.textContent.length;
      if (!startSet && start <= total + len) {
        range.setStart(current, Math.max(0, start - total));
        startSet = true;
      }
      if (!endSet && end <= total + len) {
        range.setEnd(current, Math.max(0, end - total));
        endSet = true;
        break;
      }
      total += len;
    }
    if (!startSet || !endSet) return null;
    return range;
  }

  // ---------------------------------------------------------------------
  // Anchoring — mirrors src/lib/review/anchor-comments.ts. Kept in sync by
  // hand since this file must stay a single dependency-free artifact.
  // ---------------------------------------------------------------------
  function findAllOccurrences(haystack, needle) {
    if (!needle) return [];
    var positions = [];
    var from = 0;
    for (;;) {
      var idx = haystack.indexOf(needle, from);
      if (idx === -1) break;
      positions.push(idx);
      from = idx + 1;
    }
    return positions;
  }

  function locateAnchor(text, anchorText, prefix, suffix) {
    if (!anchorText) return null;
    var positions = findAllOccurrences(text, anchorText);
    if (positions.length === 0) return null;
    if (positions.length === 1) {
      return { start: positions[0], end: positions[0] + anchorText.length };
    }
    var candidates = positions.filter(function (start) {
      var end = start + anchorText.length;
      var before = text.slice(0, start);
      var after = text.slice(end);
      var prefixOk = !prefix || before.slice(-prefix.length) === prefix;
      var suffixOk = !suffix || after.slice(0, suffix.length) === suffix;
      return prefixOk && suffixOk;
    });
    if (candidates.length !== 1) return null;
    return { start: candidates[0], end: candidates[0] + anchorText.length };
  }

  function applyMarkForComment(comment) {
    var text = docEl.textContent;
    var pos = locateAnchor(text, comment.anchorText, comment.prefix, comment.suffix);
    if (!pos) return;
    var range = findRangeForOffsets(docEl, pos.start, pos.end);
    if (!range) return;
    wrapRangeWithMark(range, comment.id);
  }

  function wrapRangeWithMark(range, commentId) {
    var startNode = range.startContainer, startOffset = range.startOffset;
    var endNode = range.endContainer, endOffset = range.endOffset;
    var walker = document.createTreeWalker(docEl, NodeFilter.SHOW_TEXT, null);
    var nodes = [];
    var inRange = false;
    var current;
    while ((current = walker.nextNode())) {
      if (current === startNode) inRange = true;
      if (inRange) nodes.push(current);
      if (current === endNode) break;
    }
    nodes.forEach(function (node) {
      var from = (node === startNode) ? startOffset : 0;
      var to = (node === endNode) ? endOffset : node.textContent.length;
      if (from >= to) return;
      var text = node.textContent;
      var before = text.slice(0, from);
      var middle = text.slice(from, to);
      var after = text.slice(to);
      var mark = document.createElement("mark");
      mark.className = "review-mark";
      mark.setAttribute("data-comment-id", commentId);
      mark.textContent = middle;
      var parent = node.parentNode;
      if (!parent) return;
      var frag = document.createDocumentFragment();
      if (before) frag.appendChild(document.createTextNode(before));
      frag.appendChild(mark);
      if (after) frag.appendChild(document.createTextNode(after));
      parent.replaceChild(frag, node);
    });
  }

  function removeMarksForComment(commentId) {
    var marks = docEl.querySelectorAll('mark.review-mark[data-comment-id="' + commentId + '"]');
    marks.forEach(function (mark) {
      var parent = mark.parentNode;
      if (!parent) return;
      while (mark.firstChild) parent.insertBefore(mark.firstChild, mark);
      parent.removeChild(mark);
      parent.normalize();
    });
  }

  function flashComment(commentId) {
    var mark = docEl.querySelector('mark.review-mark[data-comment-id="' + commentId + '"]');
    if (!mark) return;
    mark.scrollIntoView({ behavior: "smooth", block: "center" });
    mark.classList.add("flash");
    setTimeout(function () { mark.classList.remove("flash"); }, 900);
  }

  // ---------------------------------------------------------------------
  // Comment list rendering
  // ---------------------------------------------------------------------
  function renderCommentList() {
    commentsCountEl.textContent = String(comments.length);
    commentsListEl.innerHTML = "";
    if (comments.length === 0) {
      var empty = document.createElement("p");
      empty.className = "review-empty";
      empty.textContent = "No comments yet — select text in the document to add one.";
      commentsListEl.appendChild(empty);
      return;
    }
    comments.forEach(function (c) {
      var card = document.createElement("div");
      card.className = "review-comment-card";

      var excerpt = document.createElement("p");
      excerpt.className = "review-comment-excerpt";
      excerpt.textContent = c.anchorText
        ? ('"' + (c.anchorText.length > 60 ? c.anchorText.slice(0, 60) + "\\u2026" : c.anchorText) + '"')
        : "General comment";
      card.appendChild(excerpt);

      var body = document.createElement("p");
      body.className = "review-comment-body";
      body.textContent = c.body;
      card.appendChild(body);

      var del = document.createElement("button");
      del.type = "button";
      del.className = "review-comment-delete";
      del.setAttribute("aria-label", "Delete comment");
      del.textContent = "\\u00D7";
      del.addEventListener("click", function (e) {
        e.stopPropagation();
        comments = comments.filter(function (x) { return x.id !== c.id; });
        removeMarksForComment(c.id);
        renderCommentList();
        save();
      });
      card.appendChild(del);

      if (c.anchorText) {
        card.addEventListener("click", function () { flashComment(c.id); });
      }

      commentsListEl.appendChild(card);
    });
  }

  // ---------------------------------------------------------------------
  // Selection -> comment flow
  // ---------------------------------------------------------------------
  function hideSelectionPopup() {
    selectionPopup.hidden = true;
    selectionForm.hidden = true;
    selectionBody.value = "";
    pendingRange = null;
  }

  function showSelectionPopup(x, y) {
    selectionForm.hidden = true;
    selectionPopup.hidden = false;
    var popupWidth = 240;
    var left = Math.min(Math.max(8, x - popupWidth / 2), window.innerWidth - popupWidth - 8);
    var top = Math.min(y + 12, window.innerHeight - 60);
    selectionPopup.style.left = left + "px";
    selectionPopup.style.top = top + "px";
  }

  document.addEventListener("mouseup", function (e) {
    if (selectionPopup.contains(e.target)) return;
    var sel = window.getSelection();
    if (!sel || sel.isCollapsed || sel.rangeCount === 0) { hideSelectionPopup(); return; }
    var range = sel.getRangeAt(0);
    if (!docEl.contains(range.commonAncestorContainer)) { hideSelectionPopup(); return; }
    if (range.toString().trim().length === 0) { hideSelectionPopup(); return; }
    pendingRange = range.cloneRange();
    showSelectionPopup(e.clientX, e.clientY);
  });

  document.addEventListener("mousedown", function (e) {
    if (!selectionPopup.contains(e.target) && e.target !== docEl && !docEl.contains(e.target)) {
      hideSelectionPopup();
    }
  });

  selectionCommentBtn.addEventListener("click", function () {
    selectionForm.hidden = false;
    selectionBody.focus();
  });

  selectionCancel.addEventListener("click", hideSelectionPopup);

  selectionSave.addEventListener("click", function () {
    if (!pendingRange) return;
    var body = selectionBody.value.trim();
    if (!body) { selectionBody.focus(); return; }

    var text = docEl.textContent;
    var start = getTextOffset(docEl, pendingRange.startContainer, pendingRange.startOffset);
    var end = getTextOffset(docEl, pendingRange.endContainer, pendingRange.endOffset);
    if (end < start) { var tmp = start; start = end; end = tmp; }
    var anchorText = text.slice(start, end);
    var prefix = text.slice(Math.max(0, start - CONTEXT_LEN), start);
    var suffix = text.slice(end, end + CONTEXT_LEN);

    var comment = { id: genId(), anchorText: anchorText, prefix: prefix, suffix: suffix, body: body };
    comments.push(comment);
    wrapRangeWithMark(pendingRange, comment.id);
    window.getSelection().removeAllRanges();
    hideSelectionPopup();
    renderCommentList();
    save();
  });

  addNoteBtn.addEventListener("click", function () {
    var body = noteBodyInput.value.trim();
    if (!body) { noteBodyInput.focus(); return; }
    comments.push({ id: genId(), anchorText: "", prefix: "", suffix: "", body: body });
    noteBodyInput.value = "";
    renderCommentList();
    save();
  });

  nameInput.addEventListener("input", save);
  nameInput.addEventListener("blur", save);

  editToggle.addEventListener("change", function () {
    docEl.setAttribute("contenteditable", editToggle.checked ? "true" : "false");
    save();
  });

  // ---------------------------------------------------------------------
  // Send back — downloads the .fragment-review.json return payload, then
  // opens a prefilled mailto to the author. mailto can't carry attachments,
  // so the email body says so plainly and asks the reviewer to attach the
  // file that was just downloaded.
  // ---------------------------------------------------------------------
  function sanitizeFilename(name) {
    var out = name.trim().toLowerCase().replace(/\\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    return out || "untitled";
  }

  sendBtn.addEventListener("click", function () {
    var reviewerName = nameInput.value.trim() || "Anonymous reviewer";
    var edited = !!editToggle.checked;
    var currentText = docEl.innerText || docEl.textContent;
    var editedFullText = (edited && currentText.trim() !== originalText.trim()) ? currentText : undefined;

    var payload = {
      docId: DOC_ID,
      reviewerName: reviewerName,
      timestamp: Date.now(),
      comments: comments,
    };
    if (editedFullText !== undefined) payload.editedFullText = editedFullText;

    var filename = (FILENAME_STEM || sanitizeFilename(TITLE)) + ".fragment-review.json";
    var blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" });
    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(function () { URL.revokeObjectURL(url); }, 1000);

    var bodyLines = [
      reviewerName + " here — I reviewed \\"" + TITLE + "\\" and left " + comments.length + " comment" + (comments.length === 1 ? "" : "s") + ".",
      "",
      "This browser just downloaded a file called \\"" + filename + "\\" to your Downloads folder.",
      "Email links can't attach files automatically, so please attach it to this email yourself before sending.",
    ];
    var mailBody = bodyLines.join("\\n");
    var mailto = "mailto:" + encodeURIComponent(AUTHOR_EMAIL || "") +
      "?subject=" + encodeURIComponent("Review: " + TITLE) +
      "&body=" + encodeURIComponent(mailBody);

    sendStatusEl.textContent = "Downloaded " + filename + " — attach it to the email that just opened.";

    setTimeout(function () { window.location.href = mailto; }, 300);
  });

  restore();
})();`;
